// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function FaveTile(Props) {
  return React.createElement("button", undefined, "Hello!");
}

var make = FaveTile;

var $$default = FaveTile;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
